// This file was generated by AnchorGenerator.cs
namespace Ldraw
{
public enum ModelTypes
{
invalid,
prop,
turret_base,
turret_elevated_weapon,
weapon_ranged,
projectile,
projectile_spawn,
minifig,
minifig_body,
minifig_arm_L,
minifig_arm_R,
minifig_head,
minifig_leg_L,
minifig_leg_R,
};
}
