// This file was generated by AnchorGenerator.cs
namespace Ldraw
{
public enum ModelTypes
{
invalid,
prop,
minifig,
minifig_body,
minifig_arm_L,
minifig_arm_R,
minifig_head,
minifig_leg_L,
minifig_leg_R,
};
}
