// This file was generated by AnchorGenerator.cs
using System.Collections.Generic;
namespace Ldraw
{
public static class Anchors
{
public static readonly Dictionary<string, ModelTypes> kModelAnchors = new()
{
{ "mwg_prop_anchor.dat", ModelTypes.prop },
{ "mwg_minifig_anchor.dat", ModelTypes.minifig },
{ "mwg_minifig_body_anchor.dat", ModelTypes.minifig_body },
{ "mwg_minifig_arm_L_anchor.dat", ModelTypes.minifig_arm_L },
{ "mwg_minifig_arm_R_anchor.dat", ModelTypes.minifig_arm_R },
{ "mwg_minifig_head_anchor.dat", ModelTypes.minifig_head },
{ "mwg_minifig_leg_L_anchor.dat", ModelTypes.minifig_leg_L },
{ "mwg_minifig_leg_R_anchor.dat", ModelTypes.minifig_leg_R },
};
}
}
